#!/bin/bash
pip install bash_kernel 
python -m bash_kernel.install

git clone https://github.com/mrirecon/bart/
cd bart
PARALLEL=1 make
. startup.sh
cd ..


pip install jupyter_server_proxy
jupyter serverextension enable --py jupyter_server_proxy


git clone https://github.com/mrirecon/view/
cd view
make

