#!/bin/bash
pip install bash_kernel 
python -m bash_kernel.install

VERSION=master
wget https://github.com/mrirecon/bart/archive/${VERSION}.tar.gz
tar xvzf ${VERSION}.tar.gz
cd bart-${VERSION}
PARALLEL=1 make

